name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Asia/Tokyo
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_followup: yes
          plugin_notable: yes
          plugin_notable_types: commit, pull_request, issue
          plugin_people: yes
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 30
          plugin_habits_charts_type: graph
          plugin_traffic: yes
          
